config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'categories', to: 'categories#index'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article <ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title,presence:true, length:{minimum:4,maximum:100}
    validates :description, presence:true, length:{minimum:10,maximum:1000}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

    validates :name, presence: true, length: { minimum:3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories    
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 8, maximum: 125},
                        format:{with: VALID_EMAIL_REGEX}


    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert]="You must be logged in first"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, only:[:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
 
    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 2)
    end
    
    def edit 
    end

    def new 
        @article=Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice]="Article is created Succussfully."
            redirect_to @article
        else
            render 'new'
        end 
    end

    def update
        if @article.update(article_params)
            flash[:notice]="Article updated"
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy 
        @article.destroy
        redirect_to articles_path
    end

    private

    def find_article
       @article= Article.find(params[:id]) 
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own article"
            redirect_to @article
        end
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin,  except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 4)
    end

    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
          flash[:notice] = "Category name updated successfully"
          redirect_to @category
        else
          render 'edit'
        end
    end
    
    private 

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if!(logged_in? && current_user.admin?)
            flash[:alert]="only admins can perform that action"
            redirect_to categories_path
        end
    end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end

    def about
    end    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice]="logged in successfull"
            redirect_to user            
        else
            flash.now[:alert]=" You have entered Wrong logins"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only:[:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @articles = @user.articles
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 3)
    end

    def new
        @user = User.new
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice]="Your account information updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice]="Welcome to Alpha Blog #{@user.username} You've successfully signup "
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id]= nil if @user== current_user
        flash[:notice]= "Account and all associated articles successfully deleted"
        redirect_to articles_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email,:password)
    end

    def set_user
        @user= User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert]="You can only edit your own account"
            redirect_to @user
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
    <div class= 'container'>
        <% @articles.each do |i|%>
            <div class="row justify-content-md-center">
                <div class="col-7">
                    <div class="card text-center mt-4">
                        <div class="card-header font-italic">
                            <% if i.user %>
                                By <%= link_to i.user.username, user_path(i.user) %>
                            <% end %>
                            <% if i.categories.any? %>
                                <div class="mt-1">
                                    <%= render i.categories%>
                                </div>
                            <%end%>                            
                        </div>
                        <div class="card-body">
                            <h5 class="card-title text-success font-size-32"><%= i.title%></h5>
                            <p class="card-text"><%= i.description%></p>
                            <%= link_to "View", article_path(i), class: "btn btn-outline-success" %>                      
                            <% if logged_in? && (i.user == current_user || current_user.admin?)%>
                                <%= link_to "Edit", edit_article_path(i), class: "btn btn-outline-info" %>
                                <%= link_to "Delete", article_path(i), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                            <% end %>
                        </div>
                        <div class="card-footer text-muted">
                          <small>  Created <%=time_ago_in_words(i.created_at)%> ago, Edited <%=time_ago_in_words(i.updated_at)%> ago </small>
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<%=form_with(model: @article,local: true) do |f|%>
    <p>
        <%= f.label :title%> <br/>
        <%=f.text_field :title%>
    </p>
    <p>
        <%= f.label :description%><br/>
        <%=f.text_area :description%>
    </p>

    <p>
        <%= f.label :category%><br/>
        <%= f.collection_select(:category_ids, Category.all, :id, :name,
         { prompt: "Select The Category From Below:"}, { multiple: true, size: 4,}) %>
    </p>

    <p>
        <%=f.submit%>
    </p>

<%end%>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="index-page">
    <h2 class='text-center pt-4'>Article Listing</h2>

    <div class="text-center mt-4 digg_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render 'article' %>

    <div class="text-center p-5 digg_pagination">
    <%= will_paginate @articles, :container => false %>
    </div>

</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing articles</h1>

<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %> </p>
<% if @article.categories.any? %>
    <div class="mt-4 mb-4">
        Categories: <%= render @article.categories%>
    </div>
<%end%>

<% if logged_in? && (@article.user == current_user || current_user.admin?)%>
    <%= link_to 'Edit', edit_article_path(@article)%> |
    <%= link_to 'Delete', article_path(@article), method: :delete, data:{confirm: "Are you sure, article with id #{@article.id}? "}%> |
<%end%>
<%= link_to 'Return to articles listing', articles_path%>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category%>

<%=form_with(model: @category,local: true) do |f|%>
    <p>
        <%= f.label :name%> <br/>
        <%=f.text_field :name%>
    </p>

    <p>
        <%=f.submit%>
    </p>

<%end%>

app/views/categories/edit.html.erb
<h1>Edit a category name!</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

    <div class= 'container'>
        <% @categories.each do |i|%>
            <div class="row justify-content-md-center">
                <div class="col-7">
                    <div class="card text-center mt-4">
                        <div class="card-body">
                            <h5 class="card-title text-success font-size-32"><%= link_to i.name, category_path(i)%></h5>
                            <p class="card-text"><%= pluralize( i.articles.count, "article")%></p>                        
                        </div>
                        <div class="card-footer text-muted">
                          <small>  Created <%=time_ago_in_words(i.created_at)%> ago, Edited <%=time_ago_in_words(i.updated_at)%> ago </small>
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>

app/views/categories/new.html.erb
<h1>Create a new category!</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%=@category.name%></h1>

    <div class="text-center mt-4 digg_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

<% if logged_in? && @user == current_user.admin?%>
    <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info"%>
    </div>
<%end%>
<h3 class="text-center mt-4"> Articles </h3>

<%= render 'articles/article' %>

    <div class="text-center p-5 digg_pagination">
    <%= will_paginate @articles, :container => false %>
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Categories", categories_path, class: "nav-link"%>
      </li>

      <% if logged_in? %>

          <li class="nav-item">
            <% if current_user.admin? %>
              <%= link_to "Admin_"+current_user.username, user_path(current_user), class: "nav-link text-primary" %>
            <% else %>
              <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item ">
            <%= link_to 'Delete Profile', user_path(current_user), class:"nav-link text-danger", method: :delete, data:{confirm: "Are you sure?"} %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class:"nav-link", method: :delete %>
          </li>

      <%else%>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class:"nav-link" %>
        </li>
      <li class="nav-item">
         <%= link_to 'Sign up!', signup_path, class:"nav-link" %>
      </li>

      <%end%>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/navbar' %>
    
  <% flash.each do|name, msg|%>
    <%=msg%>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Im About Page</h1>

app/views/pages/home.html.erb
<div class="container">
    <div class="jumbotron text-center">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to 'Sign up!', signup_path, class:"btn btn-success btn-lg home-btn" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <h2 class= "alert"> Error Occurs </h2>
    <% obj.errors.full_messages.each do |msg| %>
       <li> <%=msg%> </li>
    <%end%>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>

<%=form_with(model: @user,local: true) do |f|%>
    <p>
        <%= f.label :username%> <br/>
        <%=f.text_field :username%>
    </p>
    <p>
        <%= f.label :email%><br/>
        <%=f.email_field :email%>
    </p>
    <p>
        <%= f.label :password%><br/>
        <%=f.password_field :password%>
    </p>

    <p>
        <%=f.submit(@user.new_record? ? "Sign up!" : "Update Account")%>
    </p>

<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"> Welcome to Users Index </h1>

<div class="text-center mt-4 digg_pagination">
    <%= will_paginate @users, :container => false %>
</div>

<div class= 'container'>
    <% @users.each do |i|%>
        <div class="row justify-content-md-center">
            <div class="col-7">
                <div class="card text-center mt-4">
                    <div class="card-header font-italic">
                        <%= link_to i.username, i%>
                    </div>
                    <div class="card-body">
                        <p class="card-text"><%= pluralize( i.articles.count, "article")%></p>
                        <%= link_to "View profile", i, class: "btn btn-outline-success" %>        
                        <% if logged_in? %> 
                            <% if i  == current_user %>              
                                <%= link_to "Edit profile", edit_user_path(i), class: "btn btn-outline-info" %>
                            <%end%>
                            <% if current_user.admin? %>
                                <%= link_to "Delete user", user_path(i), class: "btn btn-outline-danger", method: :delete,
                                data: {confirm: "Are you sure you want to delete? "}%>
                            <%end%>

                        <%end%>
                    </div>
                    <div class="card-footer text-muted">
                        <small>  Joined <%=time_ago_in_words(i.created_at)%> ago </small>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

<div class="text-center p-5 digg_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%=@user.username%>'s profile</h1>

<% if logged_in? && @user == current_user%>
    <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info"%>
    </div>
<%end%>
<h3 class="text-center mt-4"> Articles </h3>

<%= render 'articles/article' %>